window.OpulentSite.init({
    header: {
        homeHref: 'index.html',
        brandKey: 'brand',
        brandLabel: 'Opulent Group',
        logoSrc: 'assets/images/logo_black.png',
        logoAlt: 'Opulent Group',
        nav: [
            {
                href: 'index.html',
                key: 'navPageHome',
                label: 'Home',
                children: [
                    { href: 'index.html', key: 'navHomeHero', label: 'Hero' },
                    {
                        href: 'index.html#uae-advantage',
                        key: 'navHomeUae',
                        label: 'UAE Advantage',
                        children: [
                            { href: 'index.html#uae-advantage', key: 'navHomeUaeGov', label: 'Governance' },
                            { href: 'index.html#uae-advantage', key: 'navHomeUaeStability', label: 'Stability' }
                        ]
                    },
                    {
                        href: 'index.html#ecosystem',
                        key: 'navHomeEco',
                        label: 'Ecosystem',
                        children: [
                            { href: 'index.html#ecosystem', key: 'navHomeEcoEstate', label: 'Real Estate' },
                            { href: 'index.html#ecosystem-tech', key: 'navHomeEcoTech', label: 'IT & AI' }
                        ]
                    },
                    { href: 'contact.html', key: 'navHomeContact', label: 'Contact' }
                ]
            },
            {
                href: 'about.html',
                key: 'navPageAbout',
                label: 'About Us',
                children: [
                    { href: 'about.html', key: 'navAboutHero', label: 'About Intro' },
                    { href: 'about.html#vision', key: 'navAboutVision', label: 'Vision' },
                    {
                        href: 'about.html#ecosystem',
                        key: 'navAboutEcosystem',
                        label: 'Ecosystem',
                        children: [
                            { href: 'about.html#about-sub-marketing', key: 'navAboutMarketing', label: 'Marketing' },
                            { href: 'about.html#about-sub-ai', key: 'navAboutAI', label: 'AI Automation' }
                        ]
                    },
                    { href: 'about.html#about-philosophy', key: 'navAboutPhilosophy', label: 'Philosophy' },
                    { href: 'about.html#about-solutions', key: 'navAboutSolutions', label: 'Solutions' },
                    { href: 'about.html#about-strategy', key: 'navAboutStrategy', label: 'Strategy' },
                    { href: 'contact.html', key: 'navAboutContact', label: 'Contact' }
                ]
            },
            {
                href: 'teams.html',
                key: 'navPageTeam',
                label: 'Our Team'
            },
            {
                href: 'portfolio.html',
                key: 'navPagePortfolio',
                label: 'Portfolio',
                children: [
                    { href: 'portfolio.html#portfolio-hero', key: 'navPortfolioHero', label: 'Overview' },
                    { href: 'portfolio.html#portfolio', key: 'navPortfolioActive', label: 'Active Investments' },
                    { href: 'portfolio.html#portfolio-ecosystem', key: 'navPortfolioEcosystem', label: 'Ecosystem Strength' },
                    { href: 'portfolio.html#portfolio-expansion', key: 'navPortfolioExpansion', label: 'Expansion Pipeline' }
                ]
            },
            {
                href: 'insight.html',
                key: 'navPageInsights',
                label: 'Insights',
                children: [
                    { href: 'insight.html', key: 'navInsightHero', label: 'Hero' },
                    {
                        href: 'insight.html#insight-shift',
                        key: 'navInsightShift',
                        label: 'Wealth Shift',
                        children: [
                            { href: 'insight.html#insight-sub-governance', label: 'Governance' },
                            { href: 'insight.html#insight-sub-predictability', label: 'Predictability' },
                            { href: 'insight.html#insight-sub-mobility', label: 'Mobility' },
                            { href: 'insight.html#insight-sub-vision', label: 'Vision' }
                        ]
                    },
                    {
                        href: 'insight.html#insight-system',
                        key: 'navInsightSystem',
                        label: 'Interconnected System',
                        children: [
                            { href: 'insight.html#insight-sub-real-estate', key: 'navInsightEstate', label: 'Real Estate' },
                            { href: 'insight.html#insight-sub-technology', key: 'navInsightTech', label: 'Technology' }
                        ]
                    }
                ]
            },
            {
                href: 'esg.html',
                key: 'navPageEsg',
                label: 'ESG'
            },
            {
                href: 'contact.html',
                key: 'navPageContact',
                label: 'Contact'
            }
        ],
        actions: []
    },
    translations: {
        en: {
            pageTitle: 'AML | Opulent Group',
            brand: 'Opulent Group',
            navPageHome: 'Home',
            navHomeHero: 'Executive Overview',
            navHomeUae: 'Strategic UAE Advantage',
            navHomeUaeGov: 'Regulatory Governance',
            navHomeUaeStability: 'Macroeconomic Stability',
            navHomeEco: 'Investment Ecosystem',
            navHomeEcoEstate: 'Prime Real Estate',
            navHomeEcoTech: 'Digital Infrastructure & AI',
            navHomeContact: 'Contact',
            navPageInsights: 'Insights',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'Insights Overview',
            navInsightShift: 'Global Wealth Reallocation',
            navInsightSystem: 'Interconnected Value System',
            navInsightEstate: 'Real Estate Dynamics',
            navInsightTech: 'Technology Outlook',
            navPagePortfolio: 'Portfolio',
            navPortfolioHero: 'Portfolio Overview',
            navPortfolioActive: 'Current Investment Positions',
            navPortfolioEcosystem: 'Ecosystem Synergies',
            navPortfolioExpansion: 'Expansion Pipeline',
            navPageAbout: 'About Us',
            navPageTeam: 'Our Team',
            navAboutHero: 'Company Overview',
            navAboutVision: 'Strategic Vision',
            navAboutEcosystem: 'Business Ecosystem',
            navAboutMarketing: 'Marketing Advisory',
            navAboutAI: 'AI Transformation',
            navAboutPhilosophy: 'Investment Philosophy',
            navAboutSolutions: 'Strategic Solutions',
            navAboutStrategy: 'Execution Strategy',
            navAboutContact: 'Contact',
            navPageContact: 'Contact',
            navCta: 'Request Consultation',
            amlHeroEyebrow: 'Governance by design',
            amlHeroTitle: 'Compliance & Risk Management',
            amlHeroText: 'At Al-Tharaa Capital, integrity is our cornerstone. We operate with a steadfast commitment to the highest regulatory standards, ensuring the security of our investors\' assets and the sustainability of our financial ecosystem.',
            amlHeroChip1: 'Regulatory-first controls',
            amlHeroChip2: 'Institutional transparency',
            amlStandardEyebrow: 'Institutional Standard',
            amlFrameworkTitle: 'AML & Financial Crime Prevention',
            amlFrameworkText: 'We maintain a zero-tolerance policy regarding financial crime. Our framework is rigorously aligned with international best practices and regional mandates, ensuring Al-Tharaa Capital remains a fortress of financial security.',
            amlFrameworkPoint1: 'FATF Recommendations Alignment',
            amlFrameworkPoint2: 'UAE Federal Decree-Law No. 20 of 2018',
            amlFrameworkPoint3: 'UAE Central Bank Regulatory Guidelines',
            amlFrameworkQuote: '"Transparency is not a requirement; it is our primary value proposition to every investor we serve."',
            amlSafeguardsEyebrow: 'Control architecture',
            amlSafeguardsTitle: 'Operational Safeguards',
            amlCard1Title: 'KYC',
            amlCard1Text: 'Comprehensive Know Your Customer protocols for rigorous identity verification and risk profiling.',
            amlCard2Title: 'CDD / EDD',
            amlCard2Text: 'Multi-layered Customer Due Diligence and Enhanced Due Diligence for high-value entities.',
            amlCard3Title: 'Monitoring',
            amlCard3Text: 'Real-time surveillance of transaction patterns to detect and mitigate anomalous financial activities.',
            amlCard4Title: 'Sanctions',
            amlCard4Text: 'Daily automated screening against UN, OFAC, and regional UAE sanctions lists.',
            amlCard5Title: 'SAR',
            amlCard5Text: 'Strict Suspicious Activity Reporting channels directly linked to regional authorities.',
            amlCard6Title: 'Internal Controls',
            amlCard6Text: 'Continuous independent auditing and governance checks by top-tier internal compliance officers.',
            amlJurisdictionEyebrow: 'Regional infrastructure',
            amlJurisdictionTitle: 'Regulatory Jurisdiction',
            amlJurisdictionText: 'Deeply embedded in the UAE\'s sophisticated financial ecosystem.',
            amlJurisdictionCard1Title: 'DIFC/ADGM Free Zones',
            amlJurisdictionCard1Text: 'Licensing and compliance within premier Middle Eastern financial hubs.',
            amlJurisdictionCard2Title: 'DFSA Alignment',
            amlJurisdictionCard2Text: 'Strict adherence to Dubai Financial Services Authority conduct of business rules.',
            amlJurisdictionCard3Title: 'SCA Guidelines',
            amlJurisdictionCard3Text: 'Regulatory reporting in sync with the UAE Securities and Commodities Authority.',
            amlJurisdictionCard4Title: 'Data Privacy',
            amlJurisdictionCard4Text: 'Aligning with the UAE Federal Data Protection Law for ultimate client confidentiality.',
            amlRiskEyebrow: 'Capital discipline',
            amlRiskTitle: 'Risk Management Strategy',
            amlRiskText: 'Our objective is the preservation of capital through sophisticated risk mitigation and radical transparency.',
            amlRiskItem1Title: 'Evaluation',
            amlRiskItem1Text: 'Quarterly stress testing and scenario analysis.',
            amlRiskItem2Title: 'Diversity',
            amlRiskItem2Text: 'Cross-asset allocation to minimize volatility.',
            amlRiskItem3Title: 'Reporting',
            amlRiskItem3Text: 'Real-time portal access for investor oversight.',
            amlRiskItem4Title: 'Full Disclosure',
            amlRiskItem4Text: 'Unambiguous fee structures and performance data.',
            amlEsgEyebrow: 'Responsible allocation',
            amlEsgOverlay: 'Investing for a sustainable future.',
            amlEsgTitle: 'ESG & Responsible Investing',
            amlEsgText: 'Environmental, Social, and Governance criteria are not just checkboxes at Al-Tharaa Capital; they are core components of our risk management framework. We believe that sustainable companies deliver superior long-term returns.',
            amlEsgPoint1: 'Ethical resource allocation',
            amlEsgPoint2: 'Social impact assessment of portfolios',
            amlEsgPoint3: 'Protecting investor interests through governance',
            bandCtaTitle: 'Ready to consult with our specialist team?',
            bandCtaButton: 'Book a strategy session',
            footerText: 'An Opulent Group. Designing wealth allocation through architectural precision and regional stability since 2010.',
            footerModel: 'Model',
            footerModel1: 'Disciplined Execution',
            footerModel2: 'Asset Allocation',
            footerModel3: 'AML',
            footerRegions: 'Regions',
            footerRegions1: 'Dubai DWC',
            footerRegions2: 'Global Network',
            footerRegions3: 'UAE Advantage',
            footerGroup: 'Group',
            footerGroup1: 'Opulent Group',
            footerGroup2: 'Career Opportunities',
            footerGroup3: 'Contact Terminal',
            footerBottom: '© 2024 Opulent Prime Investment DWC LLC. All rights reserved. Diversify intelligently.',
            footerLegalPrivacy: 'Privacy Policy',
            footerLegalTerms: 'Terms of Service'
        },
        ar: {
            pageTitle: 'مكافحة غسل الأموال | مجموعة أوبولنت',
            brand: 'مجموعة أوبولنت',
            navPageHome: 'الرئيسية',
            navHomeHero: 'نظرة تنفيذية',
            navHomeUae: 'الميزة الاستراتيجية للإمارات',
            navHomeUaeGov: 'الحوكمة التنظيمية',
            navHomeUaeStability: 'الاستقرار الاقتصادي الكلي',
            navHomeEco: 'منظومة الاستثمار',
            navHomeEcoEstate: 'العقارات المميزة',
            navHomeEcoTech: 'البنية الرقمية والذكاء الاصطناعي',
            navHomeContact: 'التواصل',
            navPageInsights: 'الرؤى',
            navPageEsg: 'الاستدامة والمسؤولية',
            navPageAml: 'مكافحة غسل الأموال',
            navInsightHero: 'نظرة عامة على الرؤى',
            navInsightShift: 'إعادة توزيع الثروة العالمية',
            navInsightSystem: 'منظومة القيمة المترابطة',
            navInsightEstate: 'ديناميكيات العقارات',
            navInsightTech: 'توقعات التكنولوجيا',
            navPagePortfolio: 'المحفظة',
            navPortfolioHero: 'نظرة عامة على المحفظة',
            navPortfolioActive: 'الاستثمارات الحالية',
            navPortfolioEcosystem: 'تكامل المنظومة',
            navPortfolioExpansion: 'التوسع المستمر',
            navPageAbout: 'من نحن',
            navPageTeam: 'فريقنا',
            navAboutHero: 'نظرة عامة على الشركة',
            navAboutVision: 'الرؤية الاستراتيجية',
            navAboutEcosystem: 'منظومة الأعمال',
            navAboutMarketing: 'الاستشارات التسويقية',
            navAboutAI: 'التحول بالذكاء الاصطناعي',
            navAboutPhilosophy: 'فلسفة الاستثمار',
            navAboutSolutions: 'الحلول الاستراتيجية',
            navAboutStrategy: 'استراتيجية التنفيذ',
            navAboutContact: 'التواصل',
            navPageContact: 'التواصل',
            navCta: 'طلب استشارة',
            amlHeroEyebrow: 'الحوكمة بالتصميم',
            amlHeroTitle: 'الامتثال وإدارة المخاطر',
            amlHeroText: 'في الثريا كابيتال، النزاهة هي ركيزتنا الأساسية. نعمل بالتزام ثابت بأعلى المعايير التنظيمية لضمان أمن أصول المستثمرين واستدامة منظومتنا المالية.',
            amlHeroChip1: 'ضوابط تنظيمية أولاً',
            amlHeroChip2: 'شفافية مؤسسية',
            amlStandardEyebrow: 'المعيار المؤسسي',
            amlFrameworkTitle: 'مكافحة غسل الأموال ومنع الجرائم المالية',
            amlFrameworkText: 'نتبع سياسة صارمة لا تتسامح مع الجرائم المالية. ويعتمد إطارنا على أفضل الممارسات الدولية والمتطلبات الإقليمية بما يضمن بقاء الثريا كابيتال حصناً للأمن المالي.',
            amlFrameworkPoint1: 'التوافق مع توصيات مجموعة العمل المالي',
            amlFrameworkPoint2: 'المرسوم بقانون اتحادي رقم 20 لسنة 2018 في دولة الإمارات',
            amlFrameworkPoint3: 'إرشادات مصرف الإمارات العربية المتحدة المركزي',
            amlFrameworkQuote: '"الشفافية ليست متطلباً فحسب، بل هي القيمة الأساسية التي نقدمها لكل مستثمر نخدمه."',
            amlSafeguardsEyebrow: 'هندسة الضوابط',
            amlSafeguardsTitle: 'الضمانات التشغيلية',
            amlCard1Title: 'اعرف عميلك',
            amlCard1Text: 'بروتوكولات شاملة لمعرفة العميل للتحقق الصارم من الهوية وتقييم المخاطر.',
            amlCard2Title: 'العناية الواجبة',
            amlCard2Text: 'عناية واجبة متعددة المستويات ومعززة للكيانات عالية القيمة.',
            amlCard3Title: 'المراقبة',
            amlCard3Text: 'مراقبة فورية لأنماط المعاملات لاكتشاف الأنشطة المالية غير الاعتيادية والحد منها.',
            amlCard4Title: 'العقوبات',
            amlCard4Text: 'فحص يومي آلي مقابل قوائم عقوبات الأمم المتحدة وOFAC والقوائم الإقليمية في دولة الإمارات.',
            amlCard5Title: 'التقارير المشبوهة',
            amlCard5Text: 'قنوات صارمة للإبلاغ عن الأنشطة المشبوهة مرتبطة مباشرة بالجهات الإقليمية المختصة.',
            amlCard6Title: 'الضوابط الداخلية',
            amlCard6Text: 'تدقيق مستقل مستمر وفحوص حوكمة يقودها كبار مسؤولي الامتثال.',
            amlJurisdictionEyebrow: 'البنية التنظيمية الإقليمية',
            amlJurisdictionTitle: 'الولاية التنظيمية',
            amlJurisdictionText: 'مرتكزة بعمق داخل المنظومة المالية المتطورة في دولة الإمارات.',
            amlJurisdictionCard1Title: 'المناطق الحرة DIFC وADGM',
            amlJurisdictionCard1Text: 'الترخيص والامتثال داخل أبرز المراكز المالية في الشرق الأوسط.',
            amlJurisdictionCard2Title: 'التوافق مع DFSA',
            amlJurisdictionCard2Text: 'التزام صارم بقواعد سلطة دبي للخدمات المالية لسلوك الأعمال.',
            amlJurisdictionCard3Title: 'إرشادات SCA',
            amlJurisdictionCard3Text: 'تقارير تنظيمية متوافقة مع هيئة الأوراق المالية والسلع في دولة الإمارات.',
            amlJurisdictionCard4Title: 'خصوصية البيانات',
            amlJurisdictionCard4Text: 'التوافق مع قانون حماية البيانات الاتحادي في دولة الإمارات لضمان أعلى درجات السرية.',
            amlRiskEyebrow: 'انضباط رأس المال',
            amlRiskTitle: 'استراتيجية إدارة المخاطر',
            amlRiskText: 'هدفنا هو الحفاظ على رأس المال عبر الحد المتطور من المخاطر والشفافية الكاملة.',
            amlRiskItem1Title: 'التقييم',
            amlRiskItem1Text: 'اختبارات ضغط وتحليل سيناريوهات بشكل ربع سنوي.',
            amlRiskItem2Title: 'التنوع',
            amlRiskItem2Text: 'توزيع عبر فئات أصول مختلفة لتقليل التقلبات.',
            amlRiskItem3Title: 'التقارير',
            amlRiskItem3Text: 'وصول فوري عبر البوابة لمتابعة المستثمرين.',
            amlRiskItem4Title: 'الإفصاح الكامل',
            amlRiskItem4Text: 'هياكل رسوم وبيانات أداء واضحة بلا لبس.',
            amlEsgEyebrow: 'تخصيص مسؤول',
            amlEsgOverlay: 'الاستثمار من أجل مستقبل مستدام.',
            amlEsgTitle: 'الاستدامة والاستثمار المسؤول',
            amlEsgText: 'المعايير البيئية والاجتماعية ومعايير الحوكمة ليست مجرد متطلبات شكلية في الثريا كابيتال، بل هي عناصر أساسية ضمن إطار إدارة المخاطر لدينا. نحن نؤمن أن الشركات المستدامة تحقق عوائد متفوقة على المدى الطويل.',
            amlEsgPoint1: 'تخصيص أخلاقي للموارد',
            amlEsgPoint2: 'تقييم الأثر الاجتماعي للمحافظ',
            amlEsgPoint3: 'حماية مصالح المستثمرين عبر الحوكمة',
            bandCtaTitle: 'هل أنتم مستعدون للتشاور مع فريقنا المتخصص؟',
            bandCtaButton: 'احجز جلسة استراتيجية',
            footerText: 'إحدى جهات مجموعة أوبولنت. نصمم توزيع الثروة بدقة معمارية واستقرار إقليمي منذ 2010.',
            footerModel: 'النموذج',
            footerModel1: 'تنفيذ منضبط',
            footerModel2: 'توزيع الأصول',
            footerModel3: 'الامتثال',
            footerRegions: 'المناطق',
            footerRegions1: 'دبي DWC',
            footerRegions2: 'شبكة عالمية',
            footerRegions3: 'ميزة الإمارات',
            footerGroup: 'المجموعة',
            footerGroup1: 'مجموعة أوبولنت',
            footerGroup2: 'الفرص المهنية',
            footerGroup3: 'مركز التواصل',
            footerBottom: '© 2024 أوبولنت برايم للاستثمار ش.ذ.م.م. جميع الحقوق محفوظة. نوّع بذكاء.',
            footerLegalPrivacy: 'سياسة الخصوصية',
            footerLegalTerms: 'شروط الخدمة'
        }
    }
});
