window.OpulentSite.init({
    header: {
        homeHref: 'index.html',
        brandKey: 'brand',
        brandLabel: 'Opulent Group',
        logoSrc: 'assets/images/logo_black.png',
        logoAlt: 'Opulent Group',
        nav: [
            { href: 'index.html', key: 'navPageHome', label: 'Home' },
            { href: 'about.html', key: 'navPageAbout', label: 'About Us' },
            { href: 'teams.html', key: 'navPageTeam', label: 'Our Team' },
            { href: 'portfolio.html', key: 'navPagePortfolio', label: 'Portfolio' },
            { href: 'insight.html', key: 'navPageInsights', label: 'Insights' },
            { href: 'esg.html', key: 'navPageEsg', label: 'ESG' },
            { href: 'aml.html', key: 'navPageAml', label: 'AML' },
            { href: 'contact.html', key: 'navPageContact', label: 'Contact' }
        ],
        actions: []
    },
    translations: {
        en: {
            pageTitle: 'ESG | Opulent Group',
            brand: 'Opulent Group',
            navPageHome: 'Home',
            navPageAbout: 'About Us',
            navPageTeam: 'Our Team',
            navPagePortfolio: 'Portfolio',
            navPageInsights: 'Insights',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navPageContact: 'Contact',
            esgHeroEyebrow: 'Responsible Capital',
            esgHeroTitle: 'ESG Commitment',
            esgHeroText: 'Our ESG framework integrates environmental stewardship, social impact, and governance discipline into every investment decision.',
            esgSectionTitle: 'Three ESG Pillars',
            esgPillar1Title: 'Environmental',
            esgPillar1Text: 'Prioritizing efficient assets, resource optimization, and long-horizon sustainability in portfolio design.',
            esgPillar2Title: 'Social',
            esgPillar2Text: 'Supporting inclusive growth through ethical partnerships, workforce development, and community value creation.',
            esgPillar3Title: 'Governance',
            esgPillar3Text: 'Applying transparent oversight, compliance controls, and accountable decision frameworks across operations.',
            footerText: 'An Opulent Group. Designing wealth allocation through architectural precision and regional stability since 2010.',
            footerModel: 'Model',
            footerModel1: 'Disciplined Execution',
            footerModel2: 'Asset Allocation',
            footerModel3: 'Compliance',
            footerRegions: 'Regions',
            footerRegions1: 'Dubai DWC',
            footerRegions2: 'Global Network',
            footerRegions3: 'UAE Advantage',
            footerGroup: 'Group',
            footerGroup1: 'Opulent Group',
            footerGroup2: 'Career Opportunities',
            footerGroup3: 'Contact Terminal',
            footerBottom: '© 2024 Opulent Prime Investment DWC LLC. All rights reserved. Diversify intelligently.'
        },
        ar: {
            pageTitle: 'الاستدامة والمسؤولية | مجموعة أوبولنت',
            brand: 'مجموعة أوبولنت',
            navPageHome: 'الرئيسية',
            navPageAbout: 'من نحن',
            navPageTeam: 'فريقنا',
            navPagePortfolio: 'المحفظة',
            navPageInsights: 'الرؤى',
            navPageEsg: 'الاستدامة والمسؤولية',
            navPageAml: 'مكافحة غسل الأموال',
            navPageContact: 'التواصل',
            esgHeroEyebrow: 'رأس مال مسؤول',
            esgHeroTitle: 'التزام ESG',
            esgHeroText: 'يدمج إطار ESG لدينا الاستدامة البيئية والأثر الاجتماعي والانضباط الحوكمي في كل قرار استثماري.',
            esgSectionTitle: 'ركائز ESG الثلاث',
            esgPillar1Title: 'البيئة',
            esgPillar1Text: 'إعطاء الأولوية للأصول الكفؤة وتحسين الموارد والاستدامة طويلة الأجل في تصميم المحافظ.',
            esgPillar2Title: 'المجتمع',
            esgPillar2Text: 'دعم النمو الشامل عبر شراكات أخلاقية وتطوير الكفاءات وخلق قيمة للمجتمع.',
            esgPillar3Title: 'الحوكمة',
            esgPillar3Text: 'تطبيق رقابة شفافة وضوابط امتثال وأطر مساءلة عبر جميع العمليات.',
            footerText: 'إحدى جهات مجموعة أوبولنت. نصمم توزيع الثروة بدقة معمارية واستقرار إقليمي منذ 2010.',
            footerModel: 'النموذج',
            footerModel1: 'تنفيذ منضبط',
            footerModel2: 'توزيع الأصول',
            footerModel3: 'الامتثال',
            footerRegions: 'المناطق',
            footerRegions1: 'دبي الجنوب',
            footerRegions2: 'شبكة عالمية',
            footerRegions3: 'ميزة الإمارات',
            footerGroup: 'المجموعة',
            footerGroup1: 'مجموعة أوبولنت',
            footerGroup2: 'الفرص المهنية',
            footerGroup3: 'مركز التواصل',
            footerBottom: '© 2024 أوبولنت برايم للاستثمار ش.ذ.م.م. جميع الحقوق محفوظة. نوّع بذكاء.'
        }
    }
});
