window.OpulentSite.init({
    translations: {
        en: {
            pageTitle: 'Insights | Opulent Group',
            brand: 'Opulent Prime',
            navPageHome: 'Home',
            navHomeHero: 'Executive Overview',
            navHomeUae: 'Strategic UAE Advantage',
            navHomeUaeGov: 'Regulatory Governance',
            navHomeUaeStability: 'Macroeconomic Stability',
            navHomeEco: 'Investment Ecosystem',
            navHomeEcoEstate: 'Prime Real Estate',
            navHomeEcoTech: 'Digital Infrastructure & AI',
            navHomeContact: 'Contact',
            navPageInsights: 'Insights',
            navPageBlog: 'Blog',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'Insights Overview',
            navInsightShift: 'Global Wealth Reallocation',
            navInsightSystem: 'Interconnected Value System',
            navInsightEstate: 'Real Estate Dynamics',
            navInsightTech: 'Technology Outlook',
            navPagePortfolio: 'Portfolio',
            navPortfolioHero: 'Portfolio Overview',
            navPortfolioActive: 'Current Investment Positions',
            navPortfolioEcosystem: 'Ecosystem Synergies',
            navPortfolioExpansion: 'Expansion Pipeline',
            navPageAbout: 'About Us',
            navPageTeam: 'Our Team',
            navAboutHero: 'Company Overview',
            navAboutVision: 'Strategic Vision',
            navAboutEcosystem: 'Business Ecosystem',
            navAboutMarketing: 'Marketing Advisory',
            navAboutAI: 'AI Transformation',
            navPageContact: 'Contact',
            navContactInquiry: 'Investor Relations Inquiry',
            navCta: 'Request Consultation',
            insightHeroEyebrow: 'Market Intelligence',
            insightHeroTitle: 'Why Global Investors are repositioning to the UAE',
            insightHeroText:
                'In the past decade, the definition of a “safe investment destination” has changed. It is no longer just about returns. It is about governance, predictability, mobility, and long-term economic vision.',
            insightShiftTitle: 'A Shift in Global Wealth',
            insightMarketInsights: 'Market Insights',
            insightShiftText:
                'Our ecosystem is built upon four non-negotiable pillars that define the modern sovereign experience.',
            insightPillarGovernanceTitle: 'Governance',
            insightPillarGovernanceText:
                'Robust regulatory frameworks and transparent legal systems designed for international protection.',
            insightPillarPredictabilityTitle: 'Predictability',
            insightPillarPredictabilityText:
                'Consistent infrastructure development that is continuous, not reactive, ensuring long-term asset value.',
            insightPillarMobilityTitle: 'Mobility',
            insightPillarMobilityText:
                'Strategic positioning as a neutral, global hub offering unmatched connectivity across continents.',
            insightPillarVisionTitle: 'Vision',
            insightPillarVisionText:
                'Forward-thinking ecosystems built with scalability in mind for the future digital economy.',
            insightSystemTitle: 'An Interconnected System',
            insightSystemText1:
                'From real estate to technology, from hospitality to digital economy; the growth is not isolated. It is interconnected.',
            insightSystemQuote:
                '"For an investor, that changes everything. Because it means you are not entering a market. You are entering a system designed for growth."',
            insightFocusSector: 'Focus Sector',
            insightSectorRealEstate: 'Real Estate',
            insightSectorDigital: 'Digital Economy',
            insightSectorHospitality: 'Hospitality',
            insightSectorTechnology: 'Technology'
        },
        ar: {
            pageTitle: 'الرؤى | مجموعة أوبولنت',
            brand: 'أوبولنت برايم',
            navPageHome: 'الرئيسية',
            navHomeHero: 'البداية',
            navHomeUae: 'ميزة الإمارات',
            navHomeUaeGov: 'الحوكمة',
            navHomeUaeStability: 'الاستقرار',
            navHomeEco: 'المنظومة',
            navHomeEcoEstate: 'العقارات',
            navHomeEcoTech: 'التقنية والذكاء الاصطناعي',
            navHomeContact: 'التواصل',
            navPageInsights: 'الرؤى',
            navPageBlog: 'المدونة',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'البداية',
            navInsightShift: 'تحول الثروة',
            navInsightSystem: 'النظام المتكامل',
            navInsightEstate: 'العقارات',
            navInsightTech: 'التقنية',
            navPagePortfolio: 'المحفظة',
            navPortfolioHero: 'نظرة عامة',
            navPortfolioActive: 'الاستثمارات النشطة',
            navPortfolioEcosystem: 'قوة المنظومة',
            navPortfolioExpansion: 'التوسع المستمر',
            navPageAbout: 'من نحن',
            navPageTeam: 'فريقنا',
            navAboutHero: 'مقدمة',
            navAboutVision: 'الرؤية',
            navAboutEcosystem: 'المنظومة',
            navAboutMarketing: 'التسويق',
            navAboutAI: 'أتمتة الذكاء الاصطناعي',
            navPageContact: 'التواصل',
            navContactInquiry: 'استفسار المستثمر',
            navCta: 'اطلب استشارة',
            insightHeroEyebrow: 'استخبارات السوق',
            insightHeroTitle: 'لماذا يعيد المستثمرون العالميون التموضع نحو الإمارات',
            insightHeroText:
                'خلال العقد الماضي تغيّر تعريف “وجهة الاستثمار الآمنة”. لم يعد الأمر يتعلق بالعوائد فقط، بل بالحَوْكمة وقابلية التنبؤ والحركة والرؤية الاقتصادية طويلة الأجل.',
            insightShiftTitle: 'تحوّل في الثروة العالمية',
            insightMarketInsights: 'رؤى السوق',
            insightShiftText:
                'تقوم منظومتنا على أربعة ركائز أساسية غير قابلة للتفاوض تحدد التجربة السيادية الحديثة.',
            insightPillarGovernanceTitle: 'الحَوْكمة',
            insightPillarGovernanceText:
                'أطر تنظيمية قوية وأنظمة قانونية شفافة مصممة لحماية المستثمرين دولياً.',
            insightPillarPredictabilityTitle: 'قابلية التنبؤ',
            insightPillarPredictabilityText:
                'تطوير بنية تحتية مستمر وغير تفاعلي يضمن قيمة أصول طويلة الأجل.',
            insightPillarMobilityTitle: 'الحركة',
            insightPillarMobilityText:
                'تموضع استراتيجي كمركز عالمي محايد يوفر اتصالاً استثنائياً عبر القارات.',
            insightPillarVisionTitle: 'الرؤية',
            insightPillarVisionText:
                'منظومات استشرافية قابلة للتوسع صُممت لاقتصاد رقمي مستقبلي.',
            insightSystemTitle: 'نظام مترابط',
            insightSystemText1:
                'من العقارات إلى التقنية، ومن الضيافة إلى الاقتصاد الرقمي؛ النمو ليس معزولاً بل مترابطاً.',
            insightSystemQuote:
                '"بالنسبة للمستثمر يغيّر هذا كل شيء؛ لأنك لا تدخل سوقاً، بل تدخل نظاماً مصمماً للنمو."',
            insightFocusSector: 'قطاع التركيز',
            insightSectorRealEstate: 'العقارات',
            insightSectorDigital: 'الاقتصاد الرقمي',
            insightSectorHospitality: 'الضيافة',
            insightSectorTechnology: 'التقنية'
        }
    }
});
