tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                error: "#ba1a1a",
                "secondary-container": "#cfe6f2",
                "inverse-primary": "#abc9ef",
                "primary-fixed-dim": "#abc9ef",
                "tertiary-fixed": "#d1e4ff",
                "secondary-fixed": "#cfe6f2",
                "surface-container-low": "#f3f4f5",
                background: "#f8f9fa",
                "primary-container": "#1b3b5a",
                "on-error": "#ffffff",
                "on-primary-container": "#87a5ca",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "error-container": "#ffdad6",
                tertiary: "#1b3b5a",
                "inverse-on-surface": "#f0f1f2",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#abc9ef",
                "on-background": "#191c1d",
                "on-primary-fixed-variant": "#2a4968",
                "primary-fixed": "#d1e4ff",
                "on-tertiary-container": "#002542",
                "on-surface-variant": "#43474d",
                "surface-container-highest": "#e1e3e4",
                "on-secondary-container": "#526772",
                "on-secondary-fixed-variant": "#354a53",
                primary: "#002542",
                "on-secondary-fixed": "#071e27",
                "on-primary-fixed": "#001d35",
                "inverse-surface": "#2e3132",
                "on-primary": "#ffffff",
                "surface-tint": "#436182",
                "on-tertiary-fixed-variant": "#2a4968",
                "surface-bright": "#f8f9fa",
                "tertiary-container": "#e7e8e9",
                "secondary-fixed-dim": "#b4cad6",
                "on-tertiary-fixed": "#001d35",
                "outline-variant": "#c3c6ce",
                surface: "#f8f9fa",
                outline: "#73777e",
                "surface-variant": "#e1e3e4",
                secondary: "#4c616c",
                "surface-container": "#edeeef",
                "on-surface": "#191c1d",
                "surface-container-high": "#e7e8e9",
                "surface-dim": "#d9dadb",
                "surface-container-lowest": "#ffffff",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            fontFamily: {
                headline: ["IBM Plex Sans", "UAEDirham"],
                body: ["Plus Jakarta Sans", "UAEDirham"],
                label: ["Plus Jakarta Sans", "UAEDirham"],
            },
        },
    },
};
