window.OpulentSite.init({
    header: {
        homeHref: 'index.html',
        brandKey: 'brand',
        brandLabel: 'Opulent Group',
        logoSrc: 'assets/images/OPI-DWC.png',
        logoAlt: 'Opulent Group',
        nav: [
            {
                href: 'index.html',
                key: 'navPageHome',
                label: 'Home',
                children: [
                    {
                        href: 'index.html#uae-advantage',
                        key: 'navHomeUae',
                        label: 'UAE Advantage',
                        children: [
                            { href: 'index.html#uae-advantage', key: 'navHomeUaeGov', label: 'Governance' },
                            { href: 'index.html#uae-advantage', key: 'navHomeUaeStability', label: 'Stability' }
                        ]
                    },
                    {
                        href: 'index.html#ecosystem',
                        key: 'navHomeEco',
                        label: 'Ecosystem',
                        children: [
                            { href: 'index.html#ecosystem', key: 'navHomeEcoEstate', label: 'Real Estate' },
                            { href: 'index.html#ecosystem', key: 'navHomeEcoTech', label: 'IT & AI' }
                        ]
                    },
                    { href: 'contact.html', key: 'navHomeContact', label: 'Contact' }
                ]
            },
            {
                href: 'about.html',
                key: 'navPageAbout',
                label: 'About Us',
                children: [
                    { href: 'about.html', key: 'navAboutHero', label: 'About Intro' },
                    { href: 'about.html#vision', key: 'navAboutVision', label: 'Vision' },
                    {
                        href: 'about.html#ecosystem',
                        key: 'navAboutEcosystem',
                        label: 'Ecosystem',
                        children: [
                            { href: 'about.html#ecosystem', key: 'navAboutMarketing', label: 'Marketing' },
                            { href: 'about.html#ecosystem', key: 'navAboutAI', label: 'AI Automation' }
                        ]
                    },
                    { href: 'about.html#about-philosophy', key: 'navAboutPhilosophy', label: 'Philosophy' },
                    { href: 'about.html#about-solutions', key: 'navAboutSolutions', label: 'Solutions' },
                    { href: 'about.html#about-strategy', key: 'navAboutStrategy', label: 'Strategy' },
                    { href: 'contact.html', key: 'navAboutContact', label: 'Contact' }
                ]
            },
            {
                href: 'teams.html',
                key: 'navPageTeam',
                label: 'Our Team'
            },
            {
                href: 'portfolio.html',
                key: 'navPagePortfolio',
                label: 'Portfolio',
                children: [
                    { href: 'portfolio.html#portfolio-hero', key: 'navPortfolioHero', label: 'Overview' },
                    {
                        href: 'portfolio.html#portfolio',
                        key: 'navPortfolioActive',
                        label: 'Active Investments'
                    },
                    {
                        href: 'portfolio.html#portfolio-ecosystem',
                        key: 'navPortfolioEcosystem',
                        label: 'Ecosystem Strength'
                    },
                    {
                        href: 'portfolio.html#portfolio-expansion',
                        key: 'navPortfolioExpansion',
                        label: 'Expansion Pipeline'
                    }
                ]
            },
            {
                href: 'insight.html',
                key: 'navPageInsights',
                label: 'Insights',
                children: [
                    { href: 'insight.html', key: 'navInsightHero', label: 'Hero' },
                    {
                        href: 'insight.html#insight-shift',
                        key: 'navInsightShift',
                        label: 'Wealth Shift',
                        children: [
                            { href: 'insight.html#insight-shift', label: 'Governance' },
                            { href: 'insight.html#insight-shift', label: 'Predictability' },
                            { href: 'insight.html#insight-shift', label: 'Mobility' },
                            { href: 'insight.html#insight-shift', label: 'Vision' }
                        ]
                    },
                    {
                        href: 'insight.html#insight-system',
                        key: 'navInsightSystem',
                        label: 'Interconnected System',
                        children: [
                            { href: 'insight.html#insight-system', key: 'navInsightEstate', label: 'Real Estate' },
                            { href: 'insight.html#insight-system', key: 'navInsightTech', label: 'Technology' }
                        ]
                    }
                ]
            },
            {
                href: 'esg.html',
                key: 'navPageEsg',
                label: 'ESG'
            },
            {
                href: 'contact.html',
                key: 'navPageContact',
                label: 'Contact'
            }
        ],
        actions: []
    },
    translations: {
        en: {
            pageTitle: 'Leadership | Opulent Prime Investment',
            brand: 'Opulent Prime Investment',
            navPageHome: 'Home',
            navHomeHero: 'Executive Overview',
            navHomeUae: 'Strategic UAE Advantage',
            navHomeUaeGov: 'Regulatory Governance',
            navHomeUaeStability: 'Macroeconomic Stability',
            navHomeEco: 'Investment Ecosystem',
            navHomeEcoEstate: 'Prime Real Estate',
            navHomeEcoTech: 'Digital Infrastructure & AI',
            navHomeContact: 'Contact',
            navPageInsights: 'Insights',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'Market Perspective',
            navInsightShift: 'Capital Reallocation',
            navInsightSystem: 'Integrated Value System',
            navInsightEstate: 'Real Estate',
            navInsightTech: 'Technology',
            navPagePortfolio: 'Portfolio',
            navPortfolioHero: 'Portfolio Overview',
            navPortfolioActive: 'Active Positions',
            navPortfolioEcosystem: 'Integrated Ecosystem',
            navPortfolioExpansion: 'Expansion Pipeline',
            navPageAbout: 'About',
            navPageTeam: 'Our Team',
            navAboutHero: 'Firm Overview',
            navAboutVision: 'Mandate & Vision',
            navAboutEcosystem: 'Investment Verticals',
            navAboutMarketing: 'Brand & Marketing',
            navAboutAI: 'Technology & AI',
            navAboutPhilosophy: 'Investment Philosophy',
            navAboutSolutions: 'Allocation Framework',
            navAboutStrategy: 'Capital Model',
            navAboutContact: 'Contact',
            navPageContact: 'Contact',
            navContactInquiry: 'Investor Inquiry',
            navCta: 'Request Consultation',
            teamsHeroEyebrow: 'Leadership & Governance',
            teamsHeroTitle: 'Institutional expertise.<br>Long-term mandate.',
            teamsHeroText: 'Opulent Prime Investment is led by professionals with deep experience in institutional asset management, capital structuring, and multi-sector portfolio oversight across the UAE and global markets.',
            teamsHeroPrimary: 'View Our Portfolio',
            teamsHeroSecondary: 'Request a Consultation',
            teamsSectionExec: 'Executive Leadership',
            teamsExecBlurb: 'The principals responsible for the firm\'s investment mandate, governance framework, and long-term capital strategy.',
            teamsCeoBio: 'Muhammad Asif Pervaiz brings over three decades of institutional experience to the firm\'s leadership. His mandate centres on capital preservation, disciplined allocation, and the long-term structural integrity of the portfolio.',
            teamsSectionAD: 'Investment & Advisory',
            teamsADIntro: 'Specialist professionals',
            teamsADBlurb: 'A cross-functional team responsible for research, sector allocation, regulatory alignment, and active portfolio oversight across the firm\'s investment lifecycle.',
            teamsAD1Focus: 'Strategic asset allocation',
            teamsAD2Focus: 'Portfolio management',
            teamsAD3Focus: 'Institutional advisory',
            teamsAD4Focus: 'Economic research & analysis',
            teamsAD5Focus: 'Compliance & risk management',
            teamsAD6Focus: 'Global market operations',
            teamsSMEyebrow: 'Client Relations',
            teamsSectionSM: 'Investor Relations',
            teamsSMIntro: 'Dedicated relationship management ensuring every investor engagement is handled with discretion, professionalism, and alignment to long-term capital objectives.',
            teamsSMLiaison: 'Dedicated relationship manager',
            teamsSM1Role: 'Regional Investor Relations',
            teamsSM2Role: 'Institutional Partnerships',
            teamsSM3Role: 'Private Wealth Advisory',
            teamsSM4Role: 'Global Accounts',
            teamsNameCeo: 'Muhammad Asif Pervaiz',
            teamsNameVp: 'Muhammad Atif Pervaiz',
            teamsNameMd: 'Sadaf Zahra',
            teamsNameAd1: 'Nilkashi',
            teamsNameAd2: 'Faisal Ahmed',
            teamsNameAd3: 'Zarnaz Guroh',
            teamsNameAd4: 'Dr. M Javed Khilji',
            teamsNameAd5: 'Hafsa Owais',
            teamsNameAd6: 'Ali Daniel',
            teamsNameSm1: 'Nakaibu Catherine',
            teamsNameSm2: 'Mohammed Bouhabila',
            teamsNameSm3: 'Shifa Sayyed',
            teamsNameSm4: 'Nada Mohammed',
            teamsRole1: 'Chairman & Chief Executive Officer',
            teamsRole2: 'Vice President & Managing Director',
            teamsRole3: 'Managing Director',
            footerText: 'Opulent Prime Investment DWC LLC. Institutional asset management headquartered in Dubai since 2010.',
            footerModel: 'Framework',
            footerModel1: 'Capital Allocation',
            footerModel2: 'Risk Management',
            footerModel3: 'AML',
            footerRegions: 'Jurisdiction',
            footerRegions1: 'Dubai DWC',
            footerRegions2: 'Global Mandate',
            footerRegions3: 'UAE Positioning',
            footerGroup: 'Firm',
            footerGroup1: 'Opulent Prime Investment',
            footerGroup2: 'Careers',
            footerGroup3: 'Investor Relations',
            footerBottom: '© 2024 Opulent Prime Investment DWC LLC. All rights reserved.',
            footerMark: 'OPULENT PRIME',
            footerOffices: 'Offices',
            footerOffice1: 'London',
            footerOffice2: 'New York',
            footerOffice3: 'Singapore',
            footerGovernance: 'Governance',
            footerGov1: 'Regulatory Compliance',
            footerGov2: 'Privacy Policy',
            footerEsg: 'ESG',
            footerEsg1: 'Sustainability Report'
        },
        ar: {
            pageTitle: 'فريقنا | أوبولنت برايم',
            brand: 'مجموعة أوبولنت',
            navPageHome: 'الرئيسية',
            navHomeHero: 'البداية',
            navHomeUae: 'ميزة الإمارات',
            navHomeUaeGov: 'الحوكمة',
            navHomeUaeStability: 'الاستقرار',
            navHomeEco: 'المنظومة',
            navHomeEcoEstate: 'العقارات',
            navHomeEcoTech: 'التقنية والذكاء الاصطناعي',
            navHomeContact: 'التواصل',
            navPageInsights: 'الرؤى',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'البداية',
            navInsightShift: 'تحول الثروة',
            navInsightSystem: 'النظام المتكامل',
            navInsightEstate: 'العقارات',
            navInsightTech: 'التقنية',
            navPagePortfolio: 'المحفظة',
            navPortfolioHero: 'نظرة عامة',
            navPortfolioActive: 'الاستثمارات النشطة',
            navPortfolioEcosystem: 'قوة المنظومة',
            navPortfolioExpansion: 'التوسع المستمر',
            navPageAbout: 'من نحن',
            navPageTeam: 'فريقنا',
            navAboutHero: 'مقدمة',
            navAboutVision: 'الرؤية',
            navAboutEcosystem: 'المنظومة',
            navAboutMarketing: 'التسويق',
            navAboutAI: 'أتمتة الذكاء الاصطناعي',
            navAboutPhilosophy: 'الفلسفة',
            navAboutSolutions: 'الحلول',
            navAboutStrategy: 'الاستراتيجية',
            navAboutContact: 'التواصل',
            navPageContact: 'التواصل',
            navContactInquiry: 'استفسار المستثمر',
            navCta: 'اطلب استشارة',
            teamsHeroEyebrow: 'مهندسو الثروة',
            teamsHeroTitle: 'خبرة<br>تقودها<br>النزاهة المؤسسية.',
            teamsHeroText:
                'تعرّف على القادة صانعي الرؤية والمستشارين المتخصصين المكرسين لحماية وترسيخ إرثك عبر رأس مال منضبط واستراتيجية ثروة معمارية لدى أوبولنت برايم.',
            teamsHeroPrimary: 'الحوكمة المؤسسية',
            teamsHeroSecondary: 'تنفيذ قائم على الاستشارة',
            teamsSectionExec: 'القيادة التنفيذية',
            teamsExecBlurb:
                'المهندسون الأساسيون لأوبولنت برايم، يوجهون المؤسسة نحو نمو دقيق واستقرار عبر الأجيال.',
            teamsCeoBio:
                'مع أكثر من ثلاثة عقود من الخبرة المؤسسية، صاغ محمد آصف برويز المبادئ الأساسية للمؤسسة: الاستقرار وإدارة المخاطر بانضباط.',
            teamsSectionAD: 'المديرون المساعدون',
            teamsADIntro: 'استراتيجيون متخصصون',
            teamsADBlurb:
                'قادة يعملون عبر الوظائف يرسخون البحث والتوزيع والمواءمة التنظيمية عبر دورة الاستثمار في المؤسسة.',
            teamsAD1Focus: 'تخصيص الأصول الاستراتيجي',
            teamsAD2Focus: 'إدارة المحافظ',
            teamsAD3Focus: 'الاستشارات المؤسسية',
            teamsAD4Focus: 'البحث الاقتصادي',
            teamsAD5Focus: 'الامتثال والمخاطر',
            teamsAD6Focus: 'عمليات الأسواق العالمية',
            teamsSMEyebrow: 'قيادة العلاقات',
            teamsSectionSM: 'مديرو نجاح العملاء',
            teamsSMIntro:
                'يضمن قادة نجاح العملاء لدينا أن تكون كل علاقة سلسة ومهنية ومتسقة مع أهداف رأس المال طويلة الأمد.',
            teamsSMLiaison: 'اتصال مخصص',
            teamsSM1Role: 'مدير مبيعات إقليمي',
            teamsSM2Role: 'شراكات مؤسسية',
            teamsSM3Role: 'قائد استراتيجية HNI',
            teamsSM4Role: 'مدير حسابات عالمي',
            teamsNameCeo: 'محمد آصف برويز',
            teamsNameVp: 'محمد عاطف برويز',
            teamsNameMd: 'صدف زهراء',
            teamsNameAd1: 'نيلاكشي',
            teamsNameAd2: 'فيصل أحمد',
            teamsNameAd3: 'زرناز غوروه',
            teamsNameAd4: 'د. إم جاويد خلجي',
            teamsNameAd5: 'حفصة أويس',
            teamsNameAd6: 'علي دانيال',
            teamsNameSm1: 'ناكايبو كاثرين',
            teamsNameSm2: 'محمد بوهبيلا',
            teamsNameSm3: 'شفاء سيد',
            teamsNameSm4: 'ندى محمد',
            teamsRole1: 'رئيس مجلس الإدارة والرئيس التنفيذي',
            teamsRole2: 'نائب المدير العام',
            teamsRole3: 'المدير العام',
            footerText: 'إحدى جهات مجموعة أوبولنت. نصمم توزيع الثروة بدقة معمارية واستقرار إقليمي منذ 2010.',
            footerModel: 'النموذج',
            footerModel1: 'تنفيذ منضبط',
            footerModel2: 'توزيع الأصول',
            footerModel3: 'الامتثال',
            footerRegions: 'المناطق',
            footerRegions1: 'دبي الجنوب',
            footerRegions2: 'شبكة عالمية',
            footerRegions3: 'ميزة الإمارات',
            footerGroup: 'المجموعة',
            footerGroup1: 'مجموعة أوبولنت',
            footerGroup2: 'الفرص المهنية',
            footerGroup3: 'مركز التواصل',
            footerBottom: '© 2024 أوبولنت برايم للاستثمار ش.ذ.م.م. جميع الحقوق محفوظة. نوّع بذكاء.',
            footerMark: 'أوبولنت جروب',
            footerOffices: 'المكاتب',
            footerOffice1: 'لندن',
            footerOffice2: 'نيويورك',
            footerOffice3: 'سنغافورة',
            footerGovernance: 'الحوكمة',
            footerGov1: 'الامتثال التنظيمي',
            footerGov2: 'سياسة الخصوصية',
            footerEsg: 'الاستدامة والمسؤولية',
            footerEsg1: 'تقرير الاستدامة'
        }
    }
});
