window.OpulentSite.init({
    header: {
        brandLabel: 'Opulent Group',
        logoAlt: 'Opulent Group'
    },
    translations: {
        en: {
            pageTitle: 'Leadership | Opulent Prime Investment',
            brand: 'Opulent Prime Investment',
            navPageHome: 'Home',
            navHomeHero: 'Executive Overview',
            navHomeUae: 'Strategic UAE Advantage',
            navHomeUaeGov: 'Regulatory Governance',
            navHomeUaeStability: 'Macroeconomic Stability',
            navHomeEco: 'Investment Ecosystem',
            navHomeEcoEstate: 'Prime Real Estate',
            navHomeEcoTech: 'Digital Infrastructure & AI',
            navHomeContact: 'Contact',
            navPageInsights: 'Insights',
            navPageBlog: 'Blog',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'Market Perspective',
            navInsightShift: 'Capital Reallocation',
            navInsightSystem: 'Integrated Value System',
            navInsightEstate: 'Real Estate',
            navInsightTech: 'Technology',
            navPagePortfolio: 'Portfolio',
            navPortfolioHero: 'Portfolio Overview',
            navPortfolioActive: 'Active Positions',
            navPortfolioEcosystem: 'Integrated Ecosystem',
            navPortfolioExpansion: 'Expansion Pipeline',
            navPageAbout: 'About',
            navPageTeam: 'Our Team',
            navAboutHero: 'Firm Overview',
            navAboutVision: 'Mandate & Vision',
            navAboutEcosystem: 'Investment Verticals',
            navAboutMarketing: 'Brand & Marketing',
            navAboutAI: 'Technology & AI',
            navAboutPhilosophy: 'Investment Philosophy',
            navAboutSolutions: 'Allocation Framework',
            navAboutStrategy: 'Capital Model',
            navAboutContact: 'Contact',
            navPageContact: 'Contact',
            navContactInquiry: 'Investor Inquiry',
            navCta: 'Request Consultation',
            teamsHeroEyebrow: 'Leadership & Governance',
            teamsHeroTitle: 'Institutional expertise.<br>Long-term mandate.',
            teamsHeroText: 'Opulent Prime Investment is led by professionals with deep experience in institutional asset management, capital structuring, and multi-sector portfolio oversight across the UAE and global markets.',
            teamsHeroPrimary: 'View Our Portfolio',
            teamsHeroSecondary: 'Request a Consultation',
            teamsSectionExec: 'Executive Leadership',
            teamsExecBlurb: 'The principals responsible for the firm\'s investment mandate, governance framework, and long-term capital strategy.',
            teamsCeoBio: 'Muhammad Asif Pervaiz brings over three decades of institutional experience to the firm\'s leadership. His mandate centres on capital preservation, disciplined allocation, and the long-term structural integrity of the portfolio.',
            teamsSectionAD: 'Investment & Advisory',
            teamsADIntro: 'Specialist professionals',
            teamsADBlurb: 'A cross-functional team responsible for research, sector allocation, regulatory alignment, and active portfolio oversight across the firm\'s investment lifecycle.',
            teamsAD1Focus: 'Strategic asset allocation',
            teamsAD2Focus: 'Portfolio management',
            teamsAD3Focus: 'Institutional advisory',
            teamsAD4Focus: 'Economic research & analysis',
            teamsAD5Focus: 'Compliance & risk management',
            teamsAD6Focus: 'Global market operations',
            teamsSMEyebrow: 'Client Relations',
            teamsSectionSM: 'Investor Relations',
            teamsSMIntro: 'Dedicated relationship management ensuring every investor engagement is handled with discretion, professionalism, and alignment to long-term capital objectives.',
            teamsSMLiaison: 'Dedicated relationship manager',
            teamsSM1Role: 'Regional Investor Relations',
            teamsSM2Role: 'Institutional Partnerships',
            teamsSM3Role: 'Private Wealth Advisory',
            teamsSM4Role: 'Global Accounts',
            teamsNameCeo: 'Muhammad Asif Pervaiz',
            teamsNameVp: 'Muhammad Atif Pervaiz',
            teamsNameMd: 'Sadaf Zahra',
            teamsNameAd1: 'Nilkashi',
            teamsNameAd2: 'Faisal Ahmed',
            teamsNameAd3: 'Zarnaz Guroh',
            teamsNameAd4: 'Dr. M Javed Khilji',
            teamsNameAd5: 'Hafsa Owais',
            teamsNameAd6: 'Ali Daniel',
            teamsNameSm1: 'Nakaibu Catherine',
            teamsNameSm2: 'Mohammed Bouhabila',
            teamsNameSm3: 'Shifa Sayyed',
            teamsNameSm4: 'Nada Mohammed',
            teamsRole1: 'Chairman & Chief Executive Officer',
            teamsRole2: 'Vice President & Managing Director',
            teamsRole3: 'Director Finance',
        },
        ar: {
            pageTitle: 'فريقنا | أوبولنت برايم',
            brand: 'مجموعة أوبولنت',
            navPageHome: 'الرئيسية',
            navHomeHero: 'البداية',
            navHomeUae: 'ميزة الإمارات',
            navHomeUaeGov: 'الحوكمة',
            navHomeUaeStability: 'الاستقرار',
            navHomeEco: 'المنظومة',
            navHomeEcoEstate: 'العقارات',
            navHomeEcoTech: 'التقنية والذكاء الاصطناعي',
            navHomeContact: 'التواصل',
            navPageInsights: 'الرؤى',
            navPageBlog: 'المدونة',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navInsightHero: 'البداية',
            navInsightShift: 'تحول الثروة',
            navInsightSystem: 'النظام المتكامل',
            navInsightEstate: 'العقارات',
            navInsightTech: 'التقنية',
            navPagePortfolio: 'المحفظة',
            navPortfolioHero: 'نظرة عامة',
            navPortfolioActive: 'الاستثمارات النشطة',
            navPortfolioEcosystem: 'قوة المنظومة',
            navPortfolioExpansion: 'التوسع المستمر',
            navPageAbout: 'من نحن',
            navPageTeam: 'فريقنا',
            navAboutHero: 'مقدمة',
            navAboutVision: 'الرؤية',
            navAboutEcosystem: 'المنظومة',
            navAboutMarketing: 'التسويق',
            navAboutAI: 'أتمتة الذكاء الاصطناعي',
            navAboutPhilosophy: 'الفلسفة',
            navAboutSolutions: 'الحلول',
            navAboutStrategy: 'الاستراتيجية',
            navAboutContact: 'التواصل',
            navPageContact: 'التواصل',
            navContactInquiry: 'استفسار المستثمر',
            navCta: 'اطلب استشارة',
            teamsHeroEyebrow: 'مهندسو الثروة',
            teamsHeroTitle: 'خبرة<br>تقودها<br>النزاهة المؤسسية.',
            teamsHeroText:
                'تعرّف على القادة صانعي الرؤية والمستشارين المتخصصين المكرسين لحماية وترسيخ إرثك عبر رأس مال منضبط واستراتيجية ثروة معمارية لدى أوبولنت برايم.',
            teamsHeroPrimary: 'الحوكمة المؤسسية',
            teamsHeroSecondary: 'تنفيذ قائم على الاستشارة',
            teamsSectionExec: 'القيادة التنفيذية',
            teamsExecBlurb:
                'المهندسون الأساسيون لأوبولنت برايم، يوجهون المؤسسة نحو نمو دقيق واستقرار عبر الأجيال.',
            teamsCeoBio:
                'مع أكثر من ثلاثة عقود من الخبرة المؤسسية، صاغ محمد آصف برويز المبادئ الأساسية للمؤسسة: الاستقرار وإدارة المخاطر بانضباط.',
            teamsSectionAD: 'المديرون المساعدون',
            teamsADIntro: 'استراتيجيون متخصصون',
            teamsADBlurb:
                'قادة يعملون عبر الوظائف يرسخون البحث والتوزيع والمواءمة التنظيمية عبر دورة الاستثمار في المؤسسة.',
            teamsAD1Focus: 'تخصيص الأصول الاستراتيجي',
            teamsAD2Focus: 'إدارة المحافظ',
            teamsAD3Focus: 'الاستشارات المؤسسية',
            teamsAD4Focus: 'البحث الاقتصادي',
            teamsAD5Focus: 'الامتثال والمخاطر',
            teamsAD6Focus: 'عمليات الأسواق العالمية',
            teamsSMEyebrow: 'قيادة العلاقات',
            teamsSectionSM: 'مديرو نجاح العملاء',
            teamsSMIntro:
                'يضمن قادة نجاح العملاء لدينا أن تكون كل علاقة سلسة ومهنية ومتسقة مع أهداف رأس المال طويلة الأمد.',
            teamsSMLiaison: 'اتصال مخصص',
            teamsSM1Role: 'مدير مبيعات إقليمي',
            teamsSM2Role: 'شراكات مؤسسية',
            teamsSM3Role: 'قائد استراتيجية HNI',
            teamsSM4Role: 'مدير حسابات عالمي',
            teamsNameCeo: 'محمد آصف برويز',
            teamsNameVp: 'محمد عاطف برويز',
            teamsNameMd: 'صدف زهراء',
            teamsNameAd1: 'نيلاكشي',
            teamsNameAd2: 'فيصل أحمد',
            teamsNameAd3: 'زرناز غوروه',
            teamsNameAd4: 'د. إم جاويد خلجي',
            teamsNameAd5: 'حفصة أويس',
            teamsNameAd6: 'علي دانيال',
            teamsNameSm1: 'ناكايبو كاثرين',
            teamsNameSm2: 'محمد بوهبيلا',
            teamsNameSm3: 'شفاء سيد',
            teamsNameSm4: 'ندى محمد',
            teamsRole1: 'رئيس مجلس الإدارة والرئيس التنفيذي',
            teamsRole2: 'نائب المدير العام',
            teamsRole3: 'المدير العام',
        }
    }
});
