window.OpulentSite.init({
    header: {
        homeHref: 'index.html',
        brandKey: 'brand',
        brandLabel: 'Opulent Group',
        logoSrc: 'assets/images/logo_black.png',
        logoAlt: 'Opulent Group',
        nav: [
            { href: 'index.html', key: 'navPageHome', label: 'Home' },
            { href: 'about.html', key: 'navPageAbout', label: 'About Us' },
            { href: 'portfolio.html', key: 'navPagePortfolio', label: 'Portfolio' },
            { href: 'insight.html', key: 'navPageInsights', label: 'Insights' },
            { href: 'esg.html', key: 'navPageEsg', label: 'ESG' },
            { href: 'aml.html', key: 'navPageAml', label: 'AML' },
            { href: 'contact.html', key: 'navPageContact', label: 'Contact' }
        ],
        actions: []
    },
    translations: {
        en: {
            pageTitle: 'AML | Opulent Group',
            brand: 'Opulent Group',
            navPageHome: 'Home',
            navPageAbout: 'About Us',
            navPagePortfolio: 'Portfolio',
            navPageInsights: 'Insights',
            navPageEsg: 'ESG',
            navPageAml: 'AML',
            navPageContact: 'Contact',
            amlHeroEyebrow: 'Compliance Framework',
            amlHeroTitle: 'AML Standards',
            amlHeroText: 'Our anti-money laundering controls are designed to protect investor interests through rigorous screening, monitoring, and governance.',
            amlSectionTitle: 'Core AML Controls',
            amlControl1Title: 'KYC & Verification',
            amlControl1Text: 'Structured onboarding checks, identity validation, and source-of-funds review for all counterparties.',
            amlControl2Title: 'Transaction Monitoring',
            amlControl2Text: 'Continuous risk monitoring with escalation workflows for unusual activity and threshold-based alerts.',
            amlControl3Title: 'Governance & Reporting',
            amlControl3Text: 'Independent oversight, audit readiness, and regulatory reporting aligned with international AML standards.',
            contactMinimalTitle: 'Start a confidential conversation with our investment team.',
            contactMinimalText: 'Disciplined guidance for long-term capital allocation.',
            contactMinimalButton: 'Contact Our Investment Team',
            footerText: 'An Opulent Group. Designing wealth allocation through architectural precision and regional stability since 2010.',
            footerModel: 'Model',
            footerModel1: 'Disciplined Execution',
            footerModel2: 'Asset Allocation',
            footerModel3: 'Compliance',
            footerRegions: 'Regions',
            footerRegions1: 'Dubai DWC',
            footerRegions2: 'Global Network',
            footerRegions3: 'UAE Advantage',
            footerGroup: 'Group',
            footerGroup1: 'Opulent Group',
            footerGroup2: 'Career Opportunities',
            footerGroup3: 'Contact Terminal',
            footerBottom: '© 2024 Opulent Prime Investment DWC LLC. All rights reserved. Diversify intelligently.'
        },
        ar: {
            pageTitle: 'مكافحة غسل الأموال | مجموعة أوبولنت',
            brand: 'مجموعة أوبولنت',
            navPageHome: 'الرئيسية',
            navPageAbout: 'من نحن',
            navPagePortfolio: 'المحفظة',
            navPageInsights: 'الرؤى',
            navPageEsg: 'الاستدامة والمسؤولية',
            navPageAml: 'مكافحة غسل الأموال',
            navPageContact: 'التواصل',
            amlHeroEyebrow: 'إطار الامتثال',
            amlHeroTitle: 'معايير AML',
            amlHeroText: 'تم تصميم ضوابط مكافحة غسل الأموال لدينا لحماية مصالح المستثمرين عبر إجراءات فحص ومراقبة وحوكمة صارمة.',
            amlSectionTitle: 'ضوابط AML الأساسية',
            amlControl1Title: 'اعرف عميلك والتحقق',
            amlControl1Text: 'فحوصات انضمام منظمة، والتحقق من الهوية، ومراجعة مصادر الأموال لجميع الأطراف.',
            amlControl2Title: 'مراقبة المعاملات',
            amlControl2Text: 'مراقبة مستمرة للمخاطر مع مسارات تصعيد للأنشطة غير المعتادة والتنبيهات المعتمدة على الحدود.',
            amlControl3Title: 'الحوكمة والتقارير',
            amlControl3Text: 'إشراف مستقل، وجاهزية تدقيق، وتقارير تنظيمية متوافقة مع المعايير الدولية لمكافحة غسل الأموال.',
            contactMinimalTitle: 'ابدأ محادثة سرية مع فريق الاستثمار لدينا.',
            contactMinimalText: 'إرشاد منضبط لتخصيص رأس المال على المدى الطويل.',
            contactMinimalButton: 'تواصل مع فريق الاستثمار',
            footerText: 'إحدى جهات مجموعة أوبولنت. نصمم توزيع الثروة بدقة معمارية واستقرار إقليمي منذ 2010.',
            footerModel: 'النموذج',
            footerModel1: 'تنفيذ منضبط',
            footerModel2: 'توزيع الأصول',
            footerModel3: 'الامتثال',
            footerRegions: 'المناطق',
            footerRegions1: 'دبي الجنوب',
            footerRegions2: 'شبكة عالمية',
            footerRegions3: 'ميزة الإمارات',
            footerGroup: 'المجموعة',
            footerGroup1: 'مجموعة أوبولنت',
            footerGroup2: 'الفرص المهنية',
            footerGroup3: 'مركز التواصل',
            footerBottom: '© 2024 أوبولنت برايم للاستثمار ش.ذ.م.م. جميع الحقوق محفوظة. نوّع بذكاء.'
        }
    }
});
