window.OpulentSite.init({
    header: {
        homeHref: 'index.html',
        brandKey: 'brand',
        brandLabel: 'Opulent Prime',
        logoSrc: 'assets/images/logo_black.png',
        logoAlt: 'Opulent Prime',
        nav: [
            {
                href: 'index.html',
                key: 'navPageHome',
                label: 'Home',
                children: [
                    { href: '#hero', key: 'navHomeHero', label: 'Hero' },
                    {
                        href: '#uae-advantage',
                        key: 'navHomeUae',
                        label: 'UAE Advantage',
                        children: [
                            { href: '#uae-advantage', key: 'navHomeUaeGov', label: 'Governance' },
                            { href: '#uae-advantage', key: 'navHomeUaeStability', label: 'Stability' }
                        ]
                    },
                    {
                        href: '#ecosystem',
                        key: 'navHomeEco',
                        label: 'Ecosystem',
                        children: [
                            { href: '#ecosystem', key: 'navHomeEcoEstate', label: 'Real Estate' },
                            { href: '#ecosystem', key: 'navHomeEcoTech', label: 'IT & AI' }
                        ]
                    },
                    { href: '#contact', key: 'navHomeContact', label: 'Contact' }
                ]
            },
            {
                href: 'insight.html',
                key: 'navPageInsights',
                label: 'Insights',
                children: [
                    { href: 'insight.html#insight-hero', key: 'navInsightHero', label: 'Hero' },
                    { href: 'insight.html#insight-shift', key: 'navInsightShift', label: 'Wealth Shift' },
                    {
                        href: 'insight.html#insight-system',
                        key: 'navInsightSystem',
                        label: 'Interconnected System',
                        children: [
                            { href: 'insight.html#insight-sub-real-estate', key: 'navInsightEstate', label: 'Real Estate' },
                            { href: 'insight.html#insight-sub-technology', key: 'navInsightTech', label: 'Technology' }
                        ]
                    }
                ]
            },
            {
                href: 'portfolio.html',
                key: 'navPagePortfolio',
                label: 'Portfolio',
                children: [
                    { href: 'portfolio.html#portfolio-hero', key: 'navPortfolioHero', label: 'Overview' },
                    {
                        href: 'portfolio.html#portfolio-active',
                        key: 'navPortfolioActive',
                        label: 'Active Investments'
                    },
                    {
                        href: 'portfolio.html#portfolio-ecosystem',
                        key: 'navPortfolioEcosystem',
                        label: 'Ecosystem Strength'
                    },
                    {
                        href: 'portfolio.html#portfolio-expansion',
                        key: 'navPortfolioExpansion',
                        label: 'Ongoing Expansion'
                    }
                ]
            },
            {
                href: 'about.html',
                key: 'navPageAbout',
                label: 'About Us',
                children: [
                    { href: 'about.html#about-us', key: 'navAboutHero', label: 'About Intro' },
                    { href: 'about.html#vision', key: 'navAboutVision', label: 'Vision' },
                    {
                        href: 'about.html#ecosystem',
                        key: 'navAboutEcosystem',
                        label: 'Ecosystem',
                        children: [
                            { href: 'about.html#about-sub-marketing', key: 'navAboutMarketing', label: 'Marketing' },
                            { href: 'about.html#about-sub-ai', key: 'navAboutAI', label: 'AI Automation' }
                        ]
                    }
                ]
            }
        ],
        actions: [
            {
                key: 'navCta',
                label: 'Request Consultation',
                href: '#contact',
                className: 'bg-primary text-on-primary px-5 md:px-6 py-2.5 rounded-full font-semibold hover:bg-primary-container transition-all'
            }
        ]
    },
    translations: {
        en: {
            pageTitle: 'Opulent Prime | Global Capital Management',
            brand: 'Opulent Prime',
            navPageHome: 'Home',
            navHomeHero: 'Hero',
            navHomeUae: 'UAE Advantage',
            navHomeUaeGov: 'Governance',
            navHomeUaeStability: 'Stability',
            navHomeEco: 'Ecosystem',
            navHomeEcoEstate: 'Real Estate',
            navHomeEcoTech: 'IT & AI',
            navHomeContact: 'Contact',
            navPageInsights: 'Insights',
            navInsightHero: 'Hero',
            navInsightShift: 'Wealth Shift',
            navInsightSystem: 'Interconnected System',
            navInsightEstate: 'Real Estate',
            navInsightTech: 'Technology',
            navPagePortfolio: 'Portfolio',
            navPortfolioHero: 'Overview',
            navPortfolioActive: 'Active Investments',
            navPortfolioEcosystem: 'Ecosystem Strength',
            navPortfolioExpansion: 'Ongoing Expansion',
            navPageAbout: 'About Us',
            navAboutHero: 'About Intro',
            navAboutVision: 'Vision',
            navAboutEcosystem: 'Ecosystem',
            navAboutMarketing: 'Marketing',
            navAboutAI: 'AI Automation',
            navCta: 'Request Consultation',
            heroTitle: "Global Capital Has a Direction. <span class=\"text-secondary-container\">It's Moving.</span>",
            heroText: "Shift from the erosion of uncertainty to the sanctuary of structured stability. We navigate the transition of wealth into the world's most resilient growth corridors.",
            heroPrimary: 'Explore Investment Model',
            heroSecondary: 'View Ecosystem',
            metricLabel: 'Growth Forecast',
            metricValue: 'UAE 2030',
            metricText: 'Strategically positioned in the Dubai DWC corridor, capturing the influx of global capital seeking institutional-grade security.',
            visionEyebrow: 'Wealth Preservation',
            visionTitle: 'Protection against the erosion of value.',
            visionText1: 'In an era where persistent inflation silently erodes liquid wealth, capital requires a new architecture. Modern prosperity is no longer about accumulation alone; it is about transition into structured opportunities that outpace devaluation.',
            visionText2: 'Opulent Prime provides the framework for this transition. We identify systemic risks in traditional markets and offer pathways into hard assets and high-growth verticals that define the next decade of global stability.',
            visionStat1: 'Strategic',
            visionStat1Label: 'Asset Allocation',
            visionStat2: 'Secured',
            visionStat2Label: 'Growth Corridors',
            uaeEyebrow: 'The Regional Anchor',
            uaeTitlePrefix: 'Why the World Is Looking at',
            uaeTitleSuffix: 'Differently.',
            uaeText: 'The Burj Khalifa is more than an engineering marvel; it is a symbol of intent. While the world grapples with stagnation, the UAE executes a long-term vision rooted in stability, legislative clarity, and aggressive innovation.',
            uaeCard1Title: 'Legislative Clarity',
            uaeCard1Text: 'A robust regulatory environment designed to welcome and protect international capital and institutional ownership.',
            uaeCard2Title: 'Geopolitical Stability',
            uaeCard2Text: 'A neutral, forward-thinking hub serving as the definitive bridge between East and West trade routes.',
            uaeCard3Title: 'Visionary Growth',
            uaeCard3Text: 'Unmatched investment in infrastructure and technology, creating a permanent magnet for global talent.',
            ecoEyebrow: 'The Opulent Methodology',
            ecoTitle: 'Disciplined Execution',
            ecoQuote: '"Wealth is built by designing allocation."',
            ecoCard1Title: 'Premium Real Estate',
            ecoCard1Text: 'Direct acquisition of prime commercial and luxury residential holdings in high-velocity districts.',
            ecoCard2Title: 'Hospitality',
            ecoCard2Text: 'Strategic stakes in luxury hotel assets and high-end leisure developments.',
            ecoCard3Title: 'Luxury Assets',
            ecoCard3Text: 'Diversification into tangible luxury commodities with high historical retention.',
            ecoCard4Title: 'IT & Artificial Intelligence',
            ecoCard4Text: 'Funding the algorithmic future through early-stage exposure to AI infrastructure and fintech.',
            coreStrategyTitle: 'Core Strategy & Model',
            coreStrategyText: 'A minimal allocation view designed for quick decision confidence.',
            coreStrategyItem1: 'Premium Real Estate',
            coreStrategyItem2: 'Hospitality',
            coreStrategyItem3: 'Luxury Assets',
            coreStrategyItem4: 'IT & AI',
            ctaTitle: 'Invest globally. Diversify intelligently. Grow securely in the UAE.',
            ctaText: 'Initiate a conversation with our investment committee to align your capital with our disciplined growth frameworks.',
            ctaButton: 'Start the Conversation',
            ctaNote: 'Strict confidentiality protocols applied to all inquiries.',
            footerText: 'An Opulent Group entity. Designing wealth allocation through architectural precision and regional stability since 2010.',
            footerModel: 'Model',
            footerModel1: 'Disciplined Execution',
            footerModel2: 'Asset Allocation',
            footerModel3: 'Compliance',
            footerRegions: 'Regions',
            footerRegions1: 'Dubai DWC',
            footerRegions2: 'Global Network',
            footerRegions3: 'UAE Advantage',
            footerGroup: 'Group',
            footerGroup1: 'Opulent Group',
            footerGroup2: 'Career Opportunities',
            footerGroup3: 'Contact Terminal',
            footerBottom: '© 2024 Opulent Prime Investment DWC LLC. All rights reserved. Diversify intelligently.',
            footerMark: 'OPULENT GROUP'
        },
        ar: {
            pageTitle: 'أوبولنت برايم | إدارة رأس المال العالمية',
            brand: 'أوبولنت برايم',
            navPageHome: 'الرئيسية',
            navHomeHero: 'البداية',
            navHomeUae: 'ميزة الإمارات',
            navHomeUaeGov: 'الحوكمة',
            navHomeUaeStability: 'الاستقرار',
            navHomeEco: 'المنظومة',
            navHomeEcoEstate: 'العقارات',
            navHomeEcoTech: 'التقنية والذكاء الاصطناعي',
            navHomeContact: 'التواصل',
            navPageInsights: 'الرؤى',
            navInsightHero: 'البداية',
            navInsightShift: 'تحول الثروة',
            navInsightSystem: 'النظام المتكامل',
            navInsightEstate: 'العقارات',
            navInsightTech: 'التقنية',
            navPagePortfolio: 'المحفظة',
            navPortfolioHero: 'نظرة عامة',
            navPortfolioActive: 'الاستثمارات النشطة',
            navPortfolioEcosystem: 'قوة المنظومة',
            navPortfolioExpansion: 'التوسع المستمر',
            navPageAbout: 'من نحن',
            navAboutHero: 'مقدمة',
            navAboutVision: 'الرؤية',
            navAboutEcosystem: 'المنظومة',
            navAboutMarketing: 'التسويق',
            navAboutAI: 'أتمتة الذكاء الاصطناعي',
            navCta: 'اطلب استشارة',
            heroTitle: 'رأس المال العالمي له اتجاه. <span class="text-secondary-container">وهو يتحرك.</span>',
            heroText: 'نحوّل الثروة من تآكل عدم اليقين إلى ملاذ الاستقرار المنظم، ونوجّه انتقال رأس المال إلى أكثر ممرات النمو صلابة في العالم.',
            heroPrimary: 'استكشف نموذج الاستثمار',
            heroSecondary: 'استعرض المنظومة',
            metricLabel: 'توقعات النمو',
            metricValue: 'الإمارات 2030',
            metricText: 'تموضع استراتيجي في ممر دبي الجنوب لالتقاط تدفقات رأس المال العالمي الباحث عن أمان مؤسسي عالي المستوى.',
            visionEyebrow: 'حفظ الثروة',
            visionTitle: 'حماية القيمة من التآكل.',
            visionText1: 'في عصر يلتهم فيه التضخم المستمر السيولة بصمت، تحتاج الثروة إلى هندسة جديدة. لم تعد الرفاهية الحديثة قائمة على التراكم فقط، بل على الانتقال إلى فرص منظمة تتفوق على انخفاض القيمة.',
            visionText2: 'يوفر أوبولنت برايم إطار هذا الانتقال. نحن نحدد المخاطر النظامية في الأسواق التقليدية ونبني مسارات نحو الأصول الصلبة والقطاعات عالية النمو التي تصنع استقرار العقد القادم.',
            visionStat1: 'استراتيجي',
            visionStat1Label: 'توزيع الأصول',
            visionStat2: 'مؤمّن',
            visionStat2Label: 'ممرات النمو',
            uaeEyebrow: 'المرتكز الإقليمي',
            uaeTitlePrefix: 'لماذا ينظر العالم إلى',
            uaeTitleSuffix: 'بشكل مختلف.',
            uaeText: 'برج خليفة ليس مجرد إنجاز هندسي، بل رمز للنية الواضحة. بينما يواجه العالم الركود، تنفذ الإمارات رؤية طويلة المدى قائمة على الاستقرار والوضوح التشريعي والابتكار الجريء.',
            uaeCard1Title: 'وضوح تشريعي',
            uaeCard1Text: 'بيئة تنظيمية قوية صُممت لاستقبال رأس المال الدولي وحمايته وحماية الملكية المؤسسية.',
            uaeCard2Title: 'استقرار جيوسياسي',
            uaeCard2Text: 'مركز محايد ومتقدم يمثل الجسر الحاسم بين طرق التجارة في الشرق والغرب.',
            uaeCard3Title: 'نمو صاحب رؤية',
            uaeCard3Text: 'استثمار لا مثيل له في البنية التحتية والتقنية يصنع مغناطيساً دائماً للمواهب العالمية.',
            ecoEyebrow: 'منهجية أوبولنت',
            ecoTitle: 'تنفيذ منضبط',
            ecoQuote: '"الثروة تُبنى عبر تصميم التخصيص."',
            ecoCard1Title: 'عقارات متميزة',
            ecoCard1Text: 'استحواذ مباشر على أصول تجارية وسكنية فاخرة في أكثر المناطق ديناميكية.',
            ecoCard2Title: 'الضيافة',
            ecoCard2Text: 'حصص استراتيجية في أصول الفنادق الفاخرة ومشروعات الترفيه الراقية.',
            ecoCard3Title: 'الأصول الفاخرة',
            ecoCard3Text: 'تنويع عبر سلع فاخرة ملموسة ذات احتفاظ تاريخي مرتفع بالقيمة.',
            ecoCard4Title: 'تقنية المعلومات والذكاء الاصطناعي',
            ecoCard4Text: 'تمويل المستقبل الخوارزمي عبر تعرض مبكر لبنية الذكاء الاصطناعي والتقنية المالية.',
            coreStrategyTitle: 'الاستراتيجية الأساسية والنموذج',
            coreStrategyText: 'عرض تخصيص بسيط وواضح لدعم اتخاذ القرار بسرعة.',
            coreStrategyItem1: 'عقارات متميزة',
            coreStrategyItem2: 'الضيافة',
            coreStrategyItem3: 'الأصول الفاخرة',
            coreStrategyItem4: 'تقنية المعلومات والذكاء الاصطناعي',
            ctaTitle: 'استثمر عالمياً. نوّع بذكاء. وانمُ بأمان في الإمارات.',
            ctaText: 'ابدأ حواراً مع لجنة الاستثمار لدينا لمواءمة رأس مالك مع أطر النمو المنضبطة التي نعتمدها.',
            ctaButton: 'ابدأ الحوار',
            ctaNote: 'تُطبق بروتوكولات سرية صارمة على جميع الاستفسارات.',
            footerText: 'إحدى جهات مجموعة أوبولنت. نصمم توزيع الثروة بدقة معمارية واستقرار إقليمي منذ 2010.',
            footerModel: 'النموذج',
            footerModel1: 'تنفيذ منضبط',
            footerModel2: 'توزيع الأصول',
            footerModel3: 'الامتثال',
            footerRegions: 'المناطق',
            footerRegions1: 'دبي الجنوب',
            footerRegions2: 'شبكة عالمية',
            footerRegions3: 'ميزة الإمارات',
            footerGroup: 'المجموعة',
            footerGroup1: 'مجموعة أوبولنت',
            footerGroup2: 'الفرص المهنية',
            footerGroup3: 'مركز التواصل',
            footerBottom: '© 2024 أوبولنت برايم للاستثمار ش.ذ.م.م. جميع الحقوق محفوظة. نوّع بذكاء.',
            footerMark: 'أوبولنت جروب'
        }
    }
});
